### ISSUE TITLE
Download link broken?

### ISSUE THREAD

**Issue by futureproof123** [adrian-griffin/TILDA-EFT#1]
In the /downloads folder, the readme says to download the tilda all-in-one installer, but that link is dead (atleast for me)
so I am now wondering how can I get this to run? Which release should I download?

**Comment by AminYabut** [comment]
Same for me

**Comment by AminYabut** [comment]
Link works now thank you

**Comment by adrian-griffin** [comment]
@AminYabut @futureproof123 DL link is working with the newest version, which includes an in-application updater. Just be sure to uninstall your previous Tilda download before downloading the newest (v0.9.41).

LMK if either of you run into issues

**Comment by adrian-griffin** [comment]
Also, please note that the scan key is defaulted to '~', so you should unbind '~' from the console in EFT, or change the keybind for Tilda in the settings.ini file.
